//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationParserTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleLocations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleLocations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocationParserTests.Resources.GoogleLocations", typeof(GoogleLocations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;locations&quot; : [ {
        ///    &quot;timestampMs&quot; : &quot;1483272000000&quot;,
        ///    &quot;latitudeE7&quot; : 519905099,
        ///    &quot;longitudeE7&quot; : 43898283,
        ///    &quot;accuracy&quot; : 20,
        ///    &quot;altitude&quot; : 54
        ///  }, {
        ///    &quot;timestampMs&quot; : &quot;1483358400000&quot;,
        ///    &quot;latitudeE7&quot; : 519905099,
        ///    &quot;longitudeE7&quot; : 43898283,
        ///    &quot;accuracy&quot; : 14,
        ///    &quot;altitude&quot; : 54
        ///  }, {
        ///    &quot;timestampMs&quot; : &quot;1483444800000&quot;,
        ///    &quot;latitudeE7&quot; : 519905099,
        ///    &quot;longitudeE7&quot; : 43898283,
        ///    &quot;accuracy&quot; : 14,
        ///    &quot;altitude&quot; : 54
        ///  }, {
        ///    &quot;timestampMs&quot; : &quot;1483531200000&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleTimeLine1 {
            get {
                return ResourceManager.GetString("GoogleTimeLine1", resourceCulture);
            }
        }
    }
}
